### ISSUE TITLE
Errors in log file after call of onPageContentRaw

### ISSUE THREAD

**Issue by ra1ahq** [cadjou/grav-plugin-cadphp#5]
Hello, dear Cadjou!

Recently, I noticed a lot of errors in the Grav "error" logs, with the following text:

[Fri Feb 10 00:01:22 2023] [error] [client xx.xx.xx.xx:0] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Grav\\Plugin\\Cadphp\\Cadphp::process() must be of the type string, null given, called in /home/****/public_html/user/plugins/cadphp/cadphp.php on line 35 and defined in /home/****/public_html/user/plugins/cadphp/classes/Cadphp.php:34\nStack trace:\n#0 /home/****/public_html/user/plugins/cadphp/cadphp.php(35): Grav\\Plugin\\Cadphp\\Cadphp->process(NULL)\n#1 /home/****/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Grav\\Plugin\\CadphpPlugin->onPageContentRaw(Object(RocketTheme\\Toolbox\\Event\\Event), 'onPageContentRa...', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))\n#2 /home/****/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'onPageContentRa...', Object(RocketTheme\\Toolbox\\Event\\Event))\n#3 /home/****/public_html/vendor/symfony/event-dispatcher/Even in /home/****/public_html/user/plugins/cadphp/classes/Cadphp.php on line 34

I suggest that If the method getRawContent() returns null, the next operator $content = $Cadphp->process($content); give PHP Fatal error.

I fixed this issue by adding the is_null() check in two files: "cadphp.php" and "/classes/Cadphp.php"

 if is_null(getRawContent()) $content="" . 
After this correction, I have noticed, that errors in GRAV error log dissappeared.
The page with CadPHP plugin and class works now without issues.

Mr. Cadjou, please review lines 35 and 34 in the files cadphp.php and /classes/Cadphp.php. 

Many thanks,
V.N.

**Comment by Justman10000** [comment]
@cadjou
